server {
    listen 6767;
    server_name localhost;

    location /stream/ {
        alias /home/qs-ubuntu/myStream/video/;
        add_header Access-Control-Allow-Origin *;
        proxy_pass http://localhost:3000;
    }

    location /re-serve/ {
        internal;
        alias /home/qs-ubuntu/myStream/video/;
        add_header Access-Control-Allow-Origin *;
    }
}