server {
    listen 6767;
    server_name localhost;

    location /stream/ {
        proxy_pass http://localhost:3000/transcode/;
    }

    location /re-serve/ {
        internal;
        alias /home/qs-ubuntu/myStream/video/;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Allow-Headers "*" always;
    }
}