server {
    listen 6767;
    server_name localhost;

    location /stream/ {
        alias /home/qs-ubuntu/myStream/video/;
        add_header Access-Control-Allow-Origin *;
        try_files $uri @transcode;
    }

    location @transcode {
        internal;
        rewrite ^/stream/(.*)$ /transcode/$1 break;
        proxy_pass http://localhost:3000;
    }

    location /reserve/ {
        internal;
        alias /home/qs-ubuntu/myStream/video/;
        add_header Access-Control-Allow-Origin *;
    }
}